AWSTemplateFormatVersion: 2010-09-09
Resources:
  ConfigBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'config-bucket-${AWS::Region}-${AWS::AccountId}'
      AccessControl: 'Private'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
    DeletionPolicy: Delete